Index unknown packed files better
Might help with wizzomafizzo/starcheat#63

.modpak files are the new recommended file extension.

http://community.playstarbound.com/index.php?threads/modding-with-pak-files.69950/

Right now having the .modinfo inside the .modpak doesn't seem to work.
http://i.imgur.com/PztM0TQ.png

Line 162 now checks if the mod_assets path was found from a modinfo file
and the path is not a directory it will treat it as a packed file.

The read function is still hardcoded to just .pak and .modpak because
there wasn't an obvious place to store if the asset is in a packed file
or not. Most likely will need a DB update to add the column if we get
more reports of different extensions.

If the read function doesn't know the packed files extension it will
throw an error like this:
2014-02-22 20:08:29,965 ERROR    Unable to read asset file
'/recipes/sword/eyesword/eyesword1.recipe' from
'E:\Games\SteamLibrary\SteamApps\common\Starbound\mods\EyeSwordBuilder\EyeSwordBuilder.modpak'
Traceback (most recent call last):
File "C:\Dev\Git\starcheat\build\assets.py", line 212, in read
asset = load_asset_file(asset_file)
File "C:\Dev\Git\starcheat\build\assets.py", line 38, in load_asset_file
with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory:
'E:\\Games\\SteamLibrary\\SteamApps\\common\\Starbound\\mods\\EyeSwordBuilder\\EyeSwordBuilder.modpak\\recipes/sword/eyesword/eyesword1.recipe'